name: DaRules
version: 1.0
main: com.hershesz.DaRules.DaRules
api-version: 1.16
author: Hershesz
website: https://hershesz.com/minecraft
commands:
  rules:
    description: Main usage command for Da Rules
    usage: To view all commands, use /dr help
    aliases:
      - dr
    permission: darules.use